[pytest]

minversion=7.0
testpaths=tests
python_files=test_*.py
python_classes=Test*
python_functions=test_*
norecursedirs=.smokevenv .testvenv .git __pycache__
pythonpath = .

; MARKERS
markers=
    smoke: quick sanity checks
    regression: full regression suite
    api: API tests
    e2e: E2E tests
    unit: Unit tests
    load: load tests
    ui: ui tests
    contract: validates jsonchema of responses

addopts=-v -rA --strict-markers --tb=short

log_cli=true
log_cli_level=INFO